# -*- coding: utf-8 -*-
"""Drug deaths project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EAZPipjWapS2VMZUy6cQZj96oy7wXIbt
"""

# Commented out IPython magic to ensure Python compatibility.
import os
import folium
import pandas as pd
import numpy as np
import missingno as mn
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
from sklearn.linear_model import LinearRegression
# %matplotlib inline
warnings.filterwarnings('ignore')

data_path = os.path.join(os.path.pardir, 'input', 'Accidental_Drug_Related_Deaths__2012-2017 (1).csv')
df = pd.read_csv('drug deaths.csv')
df.columns = [x.lower().replace(' ', '_') for x in df.columns]  # standardise column names
df.head()

df.info()

df.describe()

