# -*- coding: utf-8 -*-
"""nerdata mini project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ym_CzxvKji8rTuLLtmKojkIu9rvRB4jz

**Import your Libraries**
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

from scipy.stats import norm
import seaborn as sns

# %matplotlib inline

"""**Load your Data set**

"""

x = pd.read_csv ('WorldCups.csv',sep=",")

"""**Print the columns of your dataset**"""

x.info()

"""**Display the first five rows of your dataset**


"""

x.head()

"""**which is the country that has won the most worldcups?**"""

x.Winner.value_counts()

"""Brazil

**Subset the rows that belong to brazil as a worldcup winner and assign it to a dataframe called "brazil"**
"""

brazil=x[x["Winner"]=="Brazil"]

brazil.head()

"""**When was the highest scored-goals for brazil as worldcup winner?**"""

brazil.Year[brazil.GoalsScored.max()==brazil.GoalsScored]

"""**How many times has brazil qualified as a runner-up for the world cup?**"""

x[x["Runners-Up"]=="Brazil"].value_counts().sum()

"""**print the first, second and third quartile of overall goals scored**"""

np.quantile(x['GoalsScored'],[0.25,0.5,0.75])

"""**Print the variance and standard deviation of overall goalsscored using .agg() method**"""

x['GoalsScored'].agg([np.var,np.std])

"""What are the major advantages of a boxplot?

boxplots show outliers and provide a graphic display of variables spread.
"""