# -*- coding: utf-8 -*-
"""Property Prices.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xpgJiiS1GZKHw8M4l9twyj_JA5-agTPP
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
# from sklearn.preprocessing import LabelEncoder, StandardScaler, MinMaxScaler
# from sklearn.model_selection import train_test_split

df = pd.read_csv('Property Prices in Tunisia.csv')
df

df.head()

df.isnull().sum()

df.isna().sum()

df['room_count'] = df["room_count"].apply(lambda x: max(0, x))
df["bathroom_count"] = df["bathroom_count"].apply(lambda x: max(0, x))
df["size"] = df["size"].apply(lambda x: max(0, x))
df

# df.loc[df["category"] == "Terrains et Fermes", ["room_count","bathroom_count","size"]] = np.nan
# df

df.describe()

df['price'].dtype

df['room_count'] = df['room_count'].astype(int)
df['bathroom_count'] = df['bathroom_count'].astype(int)
df['size'] = df['size'].astype(int)
df

pd.options.display.float_format = '{:.2f}'.format
df.describe()

Q1 = df['price'].quantile(0.25)
Q3 = df['price'].quantile(0.75)
IQR = Q3 - Q1


lower_bound = Q1 - 1.5*IQR
upper_bound = Q3 + 1.5*IQR
outliers = df[(df['price'] < lower_bound) | (df['price'] > upper_bound)]
outliers

sns.histplot(df['price'])
plt.title('Distribution of Property Prices')
plt.xlabel('Price')
plt.show()

sns.boxplot(x='region', y='price', data=df)
plt.title('Property Prices by Region')
plt.xlabel('Region')
plt.ylabel('Price')
plt.show()

# Compute the correlation matrix and plot a heatmap
corr = df[['room_count', 'bathroom_count', 'size', 'price']].corr()
sns.heatmap(corr, annot=True, cmap='coolwarm')
plt.title('Correlation Matrix')
plt.show()